# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-01 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_wheel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hanfengshishang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=256)),
                ('price', models.IntegerField()),
                ('del_price', models.IntegerField()),
                ('buy', models.CharField(max_length=30)),
            ],
        ),
    ]
