# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-02 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_hanfengshishang'),
    ]

    operations = [
        migrations.CreateModel(
            name='f_img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_img_img', models.CharField(max_length=256)),
                ('fl_img', models.CharField(max_length=256)),
                ('fl_img21', models.CharField(max_length=256)),
                ('fl_img22', models.CharField(max_length=256)),
            ],
        ),
    ]
