# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-02 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_f_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('H_list', models.CharField(max_length=30)),
                ('s_cate1', models.CharField(max_length=30)),
            ],
        ),
    ]
